apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-manager
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account-manager
  template:
    metadata:
      labels:
        app: account-manager
    spec:
      containers:
        - name: account-manager
          image: account-manager:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: '1'

---
apiVersion: v1
kind: Service
metadata:
  name: account-manager-balancer
spec:
  selector:
    app: account-manager
  ports:
    - protocol: TCP
      port: 8000 # The port to expose to the outside
      targetPort: 8080 # The port the application is running on in the pods
  type: LoadBalancer
  sessionAffinity: ClientIP
